name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    # Optional: Set a timeout for the entire job
    timeout-minutes: 60 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      # Use an appropriate version for your project
      uses: actions/setup-python@v5 
      with:
        python-version: '3.12' 

    - name: Install Playwright
      run: |
        pip install pytest-playwright

    - name: Install Playwright Browser
      run: |
        playwright install

    - name: Install Reporting
      run: |
        pip install pytest-html

    - name: Run Playwright tests
      # Replace 'pytest' with your test command (e.g., 'python -m pytest')
      run: pytest  tests/

    - name: Upload Playwright traces (on failure)
      uses: actions/upload-artifact@v4
      # if: ${{ failure() }}
      with:
        name: playwright-traces
        path: test-result/
        retention-days: 7
